#Getting grades
m_grade = float(input("What is your math grade "))
e_grade = float(input("What is your english grade "))
ics_grade = float(input("What is your ICS grade "))
#getting info
school = input("What is your school's name ")
city = input("What city do you go to school in ")
province = input("What province do you go to school in ")
class_avg = float(input("What is the class average "))
f_name = input("What is our first name ")
l_name = input("What is your last name ")
#Processing the info
avg = round((m_grade + e_grade + ics_grade)/3, 2)
difference = abs(avg - class_avg)
#Outputting all the info
print("\t\t\t\t Student Report")
print("\t\t\t\t", school, "TDSB")
print()
print("Student name:", f_name, l_name)
print()
print("Current marks for", f_name, "are:")
print()
print("Math:\t", m_grade)
print("English:", e_grade)
print("ICS:\t", ics_grade)
print()
print("Overall average for", f_name, l_name, "is:", str(avg) + "%")
print(f_name, "is", difference, "away from the class average of", str(class_avg) + "%")
print()
print("All student reports are to be returned to:", school, "TDSB")
print()
print("City/Province:", city, " - ", province)
